

query_tickets = """
SELECT 
Q.NAME AS QUEUE_NAME, 
HD_TICKET.TITLE, 
HD_TICKET.CREATED, 
HD_TICKET.TIME_CLOSED, 
IF(HD_TICKET.HD_USE_PROCESS_STATUS and HD_TICKET.IS_PARENT, 
HD_SERVICE_STATUS.NAME, HD_STATUS.NAME) AS STATUS_NAME, 
MACHINE.NAME AS SYSTEM_NAME, 
ASSET.NAME AS ASSET_NAME, 
CTEXT.NAME AS CATEGORY_TEXT, 
S.FULL_NAME AS SUBMITTER_NAME, 
O.FULL_NAME AS OWNER_NAME, 
HD_PRIORITY.NAME AS PRIORITY  
FROM HD_TICKET  
JOIN HD_QUEUE Q ON Q.ID = HD_TICKET.HD_QUEUE_ID 
LEFT JOIN HD_SERVICE_STATUS ON HD_TICKET.HD_USE_PROCESS_STATUS and HD_TICKET.HD_SERVICE_STATUS_ID and HD_SERVICE_STATUS.ID = HD_TICKET.HD_SERVICE_STATUS_ID 
LEFT JOIN HD_STATUS ON (HD_STATUS.ID = HD_TICKET.HD_STATUS_ID) 
LEFT JOIN MACHINE ON (MACHINE.ID = HD_TICKET.MACHINE_ID) 
LEFT JOIN ASSET ON (ASSET.ID = HD_TICKET.ASSET_ID) 
LEFT JOIN HD_CATEGORY CTEXT ON (CTEXT.ID = HD_TICKET.HD_CATEGORY_ID) 
LEFT JOIN USER S ON (S.ID = HD_TICKET.SUBMITTER_ID) 
LEFT JOIN USER O ON (O.ID = HD_TICKET.OWNER_ID) 
LEFT JOIN HD_PRIORITY ON (HD_PRIORITY.ID = HD_TICKET.HD_PRIORITY_ID) 
WHERE 
-- (HD_TICKET.HD_QUEUE_ID = 15)  
-- HD_TICKET.HD_QUEUE_ID in ('15', '27')

(
    HD_TICKET.HD_QUEUE_ID = 15
)
OR
(
    HD_TICKET.HD_QUEUE_ID = 27
    AND HD_TICKET.TITLE LIKE '[*R*]%'
)

ORDER BY QUEUE_NAME
"""