
sql_query = """
# Asset Report - Cost Account: 15.0.005.00 - 20180709
select `Item`, `Type`, `ID`, `Assigned User`, if(`Unit Cost` != "", format(`Unit Cost`, 2), "") as 'Unit Cost (₦)', `COST_ACCOUNT`
from
(
/* START REMOVED 20210330
# Header Query
select
  "Cost Account:" as 'Item'
  ,COST_ACCOUNT_ASSET.NAME as 'Type'
  ,concat("Department: ", COST_ACCOUNT_ASSET_DATA.FIELD_10025) as 'ID'
  ,concat("Site: ", COST_ACCOUNT_ASSET_DATA.FIELD_10026) as 'Assigned User'
  ,"" as 'Unit Cost'
  ,null as 'ASSET_NAME'
  ,null as 'SORT_ORDER'
  ,COST_ACCOUNT_ASSET.NAME as 'COST_ACCOUNT'
  ,-1 as 'SECTION_ORDER'
from
  ASSET COST_ACCOUNT_ASSET
  join ASSET_DATA_15 COST_ACCOUNT_ASSET_DATA on COST_ACCOUNT_ASSET.ASSET_DATA_ID = COST_ACCOUNT_ASSET_DATA.ID
    and COST_ACCOUNT_ASSET.ASSET_TYPE_ID = 15 # Asset type ID 15 = "JBN Cost Accounts"
group by
  `Type`
union all
END REMOVED 20210330 */
# Computer Assets
select
  "Computer" as 'Item'
  #CONCAT('COMPUTER - LAST ONLINE -  ', LAST_INVENTORY, ')') as 'Item'
  ,TYPE_ASSET.NAME as 'Type'
  ,CONCAT(COMPUTER_ASSET.NAME, ' /',' (','LAST ONLINE:   ', LAST_INVENTORY, ')') as 'ID'
  ,COMPUTER_ASSIGNEE.USER_NAME as 'Assigned User'
  ,TYPE_ASSET_DATA.FIELD_10047 as 'Unit Cost'
  ,COMPUTER_ASSET.NAME as 'ASSET_NAME'
  ,0 as 'SORT_ORDER'
  ,COST_ACCOUNT_ASSET.NAME as 'COST_ACCOUNT'
  ,1 as 'SECTION_ORDER'
from
  ASSET COMPUTER_ASSET
  left join MACHINE M on COMPUTER_ASSET.MAPPED_ID = M.ID
  join ASSET_ASSOCIATION AA_COMPUTER_TYPE on COMPUTER_ASSET.ID = AA_COMPUTER_TYPE.ASSET_ID
    and AA_COMPUTER_TYPE.ASSET_FIELD_ID = 10031
  join ASSET TYPE_ASSET on AA_COMPUTER_TYPE.ASSOCIATED_ASSET_ID = TYPE_ASSET.ID
    and TYPE_ASSET.ASSET_TYPE_ID = 17 # ASSET TYPE ID 17 = "JBN Computer Type"
  join ASSET_DATA_17 TYPE_ASSET_DATA on TYPE_ASSET.ASSET_DATA_ID = TYPE_ASSET_DATA.ID
  join ASSET_ASSOCIATION AA_COMPUTER_COST_ACCOUNT on COMPUTER_ASSET.ID = AA_COMPUTER_COST_ACCOUNT.ASSET_ID
    and AA_COMPUTER_COST_ACCOUNT.ASSET_FIELD_ID = 10030
  join ASSET COST_ACCOUNT_ASSET on AA_COMPUTER_COST_ACCOUNT.ASSOCIATED_ASSET_ID = COST_ACCOUNT_ASSET.ID
  left join USER COMPUTER_ASSIGNEE on COMPUTER_ASSET.OWNER_ID = COMPUTER_ASSIGNEE.ID
where
  COMPUTER_ASSET.ASSET_TYPE_ID = 5
union all

# Additional PC Components
select
  ADDITIONAL_PC_COMPONENTS_ASSET.NAME as 'Item'
  ,"" as 'Type'
  ,"" as 'ID'
  ,"" as 'Assigned User'
  ,ADDITIONAL_PC_COMPONENTS_ASSET_DATA.FIELD_10053 as 'Unit Cost'
  ,COMPUTER_ASSET.NAME as 'ASSET_NAME'
  ,1 as 'SORT_ORDER'
  ,COST_ACCOUNT_ASSET.NAME as 'COST_ACCOUNT'
  ,1 as 'SECTION_ORDER'
from
  ASSET COMPUTER_ASSET
  join ASSET_ASSOCIATION AA_COMPUTER_ADDITIONAL_PC_COMPONENTS on COMPUTER_ASSET.ID = AA_COMPUTER_ADDITIONAL_PC_COMPONENTS.ASSET_ID
    and AA_COMPUTER_ADDITIONAL_PC_COMPONENTS.ASSET_FIELD_ID = 10072
  join ASSET ADDITIONAL_PC_COMPONENTS_ASSET on AA_COMPUTER_ADDITIONAL_PC_COMPONENTS.ASSOCIATED_ASSET_ID = ADDITIONAL_PC_COMPONENTS_ASSET.ID
    and ADDITIONAL_PC_COMPONENTS_ASSET.ASSET_TYPE_ID = 19 # ASSET TYPE ID 19 = "JBN Additional PC Components"
  join ASSET_DATA_19 ADDITIONAL_PC_COMPONENTS_ASSET_DATA on ADDITIONAL_PC_COMPONENTS_ASSET.ASSET_DATA_ID = ADDITIONAL_PC_COMPONENTS_ASSET_DATA.ID
  join ASSET_ASSOCIATION AA_COMPUTER_COST_ACCOUNT on COMPUTER_ASSET.ID = AA_COMPUTER_COST_ACCOUNT.ASSET_ID
    and AA_COMPUTER_COST_ACCOUNT.ASSET_FIELD_ID = 10030
  join ASSET COST_ACCOUNT_ASSET on AA_COMPUTER_COST_ACCOUNT.ASSOCIATED_ASSET_ID = COST_ACCOUNT_ASSET.ID
where
  COMPUTER_ASSET.ASSET_TYPE_ID = 5
union all

# Software (License)
select
  SC.NAME as 'Item'
  ,"" as 'Type'
  ,"" as 'ID'
  #####,"" as 'Assigned User'
   ,M.USER as  'Assigned User'
  ,LICENSE_ASSET_DATA.FIELD_6 as 'Unit Cost'
  ,COMPUTER_ASSET.NAME as 'ASSET_NAME'
  ,2 as 'SORT_ORDER'
  ,COST_ACCOUNT_ASSET.NAME as 'COST_ACCOUNT'
  ,1 as 'SECTION_ORDER'
from
  ASSET COMPUTER_ASSET
  join MACHINE M on COMPUTER_ASSET.MAPPED_ID = M.ID
  join SAM_MACHINE_JT SMJT on SMJT.MACHINE_ID = M.ID
  join CATALOG.SAM_CATALOG SC on SMJT.SAM_CATALOG_ID = SC.ID
  join ASSET_CATALOG_ASSOCIATION ACA on SC.ID = ACA.ASSOCIATED_CATALOG_ID
#    and ACA.ASSET_FIELD_ID = 24 # License
    and ACA.ASSET_FIELD_ID = 10000 # License
  join ASSET LICENSE_ASSET on ACA.ASSET_ID = LICENSE_ASSET.ID
    and LICENSE_ASSET.ASSET_TYPE_ID = 7
  join ASSET_DATA_7 LICENSE_ASSET_DATA on LICENSE_ASSET.ASSET_DATA_ID = LICENSE_ASSET_DATA.ID
  join ASSET_ASSOCIATION AA_COMPUTER_COST_ACCOUNT on COMPUTER_ASSET.ID = AA_COMPUTER_COST_ACCOUNT.ASSET_ID
    and AA_COMPUTER_COST_ACCOUNT.ASSET_FIELD_ID = 10030
  join ASSET COST_ACCOUNT_ASSET on AA_COMPUTER_COST_ACCOUNT.ASSOCIATED_ASSET_ID = COST_ACCOUNT_ASSET.ID
where
  COMPUTER_ASSET.ASSET_TYPE_ID = 5 # TYPE ID 5 = Computer Asset Type
#  and SC.SAM_TYPE IN ('TITLED_APPLICATION','TITLED_SUITE')
  and SC.SOFTWARE_CATEGORY_ID != 32
  and LICENSE_ASSET_DATA.FIELD_6 > 0
group by
  M.ID, SC.ID
union all
 
--  # Software (JBN software)
--  select
--    SPECIAL_SOFTWARE_ASSET.NAME as 'Item'
--    ,"" as 'Type'
--    ,"" as 'ID'
--    ########,"" as 'Assigned User'
--    ,M.USER as 'Assigned User'
--    ,SPECIAL_SOFTWARE_ASSET_DATA.FIELD_10017 as 'Unit Cost'
--    ,COMPUTER_ASSET.NAME as 'ASSET_NAME'
--    ,2 as 'SORT_ORDER'
--    ,COST_ACCOUNT_ASSET.NAME as 'COST_ACCOUNT'
--    ,1 as 'SECTION_ORDER'
--  from
--    ASSET COMPUTER_ASSET
--    join MACHINE M on COMPUTER_ASSET.MAPPED_ID = M.ID
--    join ASSET_ASSOCIATION AA_SPECIAL_SOFTWARE on COMPUTER_ASSET.ID = AA_SPECIAL_SOFTWARE.ASSET_ID
--      and AA_SPECIAL_SOFTWARE.ASSET_FIELD_ID = 10077
--    join ASSET SPECIAL_SOFTWARE_ASSET on AA_SPECIAL_SOFTWARE.ASSOCIATED_ASSET_ID = SPECIAL_SOFTWARE_ASSET.ID
--      and SPECIAL_SOFTWARE_ASSET.ASSET_TYPE_ID = 12
--    join ASSET_DATA_12 SPECIAL_SOFTWARE_ASSET_DATA on SPECIAL_SOFTWARE_ASSET.ASSET_DATA_ID = SPECIAL_SOFTWARE_ASSET_DATA.ID
--    join ASSET_ASSOCIATION AA_COMPUTER_COST_ACCOUNT on COMPUTER_ASSET.ID = AA_COMPUTER_COST_ACCOUNT.ASSET_ID
--      and AA_COMPUTER_COST_ACCOUNT.ASSET_FIELD_ID = 10030
--    join ASSET COST_ACCOUNT_ASSET on AA_COMPUTER_COST_ACCOUNT.ASSOCIATED_ASSET_ID = COST_ACCOUNT_ASSET.ID
--  where
--    COMPUTER_ASSET.ASSET_TYPE_ID = 5 # TYPE ID 5 = Computer Asset Type
--  group by
--    M.ID, SPECIAL_SOFTWARE_ASSET.ID
--  union all
 
 # JBN Car radio unit:
 select
   "JBN Car radio unit" as 'Item'
   ,JBN_ASSET_DATA.FIELD_10106 as 'Type'
   ,JBN_ASSET.NAME as 'ID'
   ,JBN_ASSET_DATA.FIELD_10107 as 'Assigned User'
   ,JBN_ASSET_DATA.FIELD_10109 as 'Unit Cost'
   ,JBN_ASSET.NAME as 'ASSET_NAME'
   ,0 as 'SORT_ORDER'
   ,COST_ACCOUNT_ASSET.NAME as 'COST_ACCOUNT'
   ,2 as 'SECTION_ORDER'
 from
   ASSET JBN_ASSET
   join ASSET_DATA_29 JBN_ASSET_DATA on JBN_ASSET.ASSET_DATA_ID = JBN_ASSET_DATA.ID
     and JBN_ASSET.ASSET_TYPE_ID = 29
   join ASSET_ASSOCIATION AA_JBN_COST_ACCOUNT on JBN_ASSET.ID = AA_JBN_COST_ACCOUNT.ASSET_ID
     and AA_JBN_COST_ACCOUNT.ASSET_FIELD_ID = 10110
   join ASSET COST_ACCOUNT_ASSET on AA_JBN_COST_ACCOUNT.ASSOCIATED_ASSET_ID = COST_ACCOUNT_ASSET.ID
 union all
 
 # JBN Hand radio unit:
 select
   "JBN Hand radio unit" as 'Item'
   ,JBN_ASSET_DATA.FIELD_10099 as 'Type'
   ,JBN_ASSET.NAME as 'ID'
   ,JBN_ASSET_DATA.FIELD_10092 as 'Assigned User'
   ,JBN_ASSET_DATA.FIELD_10093 as 'Unit Cost'
   ,JBN_ASSET.NAME as 'ASSET_NAME'
   ,0 as 'SORT_ORDER'
   ,COST_ACCOUNT_ASSET.NAME as 'COST_ACCOUNT'
   ,3 as 'SECTION_ORDER'
 from
   ASSET JBN_ASSET
   join ASSET_DATA_25 JBN_ASSET_DATA on JBN_ASSET.ASSET_DATA_ID = JBN_ASSET_DATA.ID
     and JBN_ASSET.ASSET_TYPE_ID = 25
   join ASSET_ASSOCIATION AA_JBN_COST_ACCOUNT on JBN_ASSET.ID = AA_JBN_COST_ACCOUNT.ASSET_ID
     and AA_JBN_COST_ACCOUNT.ASSET_FIELD_ID = 10094
   join ASSET COST_ACCOUNT_ASSET on AA_JBN_COST_ACCOUNT.ASSOCIATED_ASSET_ID = COST_ACCOUNT_ASSET.ID
 union all
 
 # JBN Ipads:
 select
   "JBN Ipads" as 'Item'
   ,IPAD_TYPE_ASSET.NAME as 'Type'
   ,JBN_ASSET.NAME as 'ID'
   ,JBN_ASSET_DATA.FIELD_10091 as 'Assigned User'
   ,IPAD_TYPE_ASSET_DATA.FIELD_10115 as 'Unit Cost'
   ,JBN_ASSET.NAME as 'ASSET_NAME'
   ,0 as 'SORT_ORDER'
   ,COST_ACCOUNT_ASSET.NAME as 'COST_ACCOUNT'
   ,4 as 'SECTION_ORDER'
 from
   ASSET JBN_ASSET
   join ASSET_DATA_24 JBN_ASSET_DATA on JBN_ASSET.ASSET_DATA_ID = JBN_ASSET_DATA.ID
     and JBN_ASSET.ASSET_TYPE_ID = 24
   join ASSET_ASSOCIATION AA_JBN_COST_ACCOUNT on JBN_ASSET.ID = AA_JBN_COST_ACCOUNT.ASSET_ID
     and AA_JBN_COST_ACCOUNT.ASSET_FIELD_ID = 10088
   join ASSET COST_ACCOUNT_ASSET on AA_JBN_COST_ACCOUNT.ASSOCIATED_ASSET_ID = COST_ACCOUNT_ASSET.ID
   join ASSET_ASSOCIATION AA_JBN_IPAD_TYPE on JBN_ASSET.ID = AA_JBN_IPAD_TYPE.ASSET_ID
     and AA_JBN_IPAD_TYPE.ASSET_FIELD_ID = 10116
   join ASSET IPAD_TYPE_ASSET on AA_JBN_IPAD_TYPE.ASSOCIATED_ASSET_ID = IPAD_TYPE_ASSET.ID
   join ASSET_DATA_31 IPAD_TYPE_ASSET_DATA on IPAD_TYPE_ASSET.ASSET_DATA_ID = IPAD_TYPE_ASSET_DATA.ID
     and IPAD_TYPE_ASSET.ASSET_TYPE_ID = 31
 union all
 
 # JBN Sattelite Phone (Thuraya):
 select
   "JBN Sattelite Phone (Thuraya)" as 'Item'
   ,SATTELITE_PHONE_TYPE_ASSET.NAME as 'Type'
   ,JBN_ASSET.NAME as 'ID'
   ,JBN_ASSET_DATA.FIELD_10089 as 'Assigned User'
   ,SATTELITE_PHONE_TYPE_ASSET_DATA.FIELD_10118 as 'Unit Cost'
   ,JBN_ASSET.NAME as 'ASSET_NAME'
   ,0 as 'SORT_ORDER'
   ,COST_ACCOUNT_ASSET.NAME as 'COST_ACCOUNT'
   ,5 as 'SECTION_ORDER'
 from
   ASSET JBN_ASSET
   join ASSET_DATA_22 JBN_ASSET_DATA on JBN_ASSET.ASSET_DATA_ID = JBN_ASSET_DATA.ID
     and JBN_ASSET.ASSET_TYPE_ID = 22
   join ASSET_ASSOCIATION AA_JBN_COST_ACCOUNT on JBN_ASSET.ID = AA_JBN_COST_ACCOUNT.ASSET_ID
     and AA_JBN_COST_ACCOUNT.ASSET_FIELD_ID = 10084
   join ASSET COST_ACCOUNT_ASSET on AA_JBN_COST_ACCOUNT.ASSOCIATED_ASSET_ID = COST_ACCOUNT_ASSET.ID
   join ASSET_ASSOCIATION AA_JBN_SATTELITE_PHONE_TYPE on JBN_ASSET.ID = AA_JBN_SATTELITE_PHONE_TYPE.ASSET_ID
     and AA_JBN_SATTELITE_PHONE_TYPE.ASSET_FIELD_ID = 10119
   join ASSET SATTELITE_PHONE_TYPE_ASSET on AA_JBN_SATTELITE_PHONE_TYPE.ASSOCIATED_ASSET_ID = SATTELITE_PHONE_TYPE_ASSET.ID
   join ASSET_DATA_32 SATTELITE_PHONE_TYPE_ASSET_DATA on SATTELITE_PHONE_TYPE_ASSET.ASSET_DATA_ID = SATTELITE_PHONE_TYPE_ASSET_DATA.ID
     and SATTELITE_PHONE_TYPE_ASSET.ASSET_TYPE_ID = 32
 union all
 
# JBN Sites & Fees:
select
  "JBN Sites & Fees" as 'Item'
  ,SITES_FEES_TYPE_ASSET.NAME as 'Type'
  ,JBN_ASSET.NAME as 'ID'
  ,"" as 'Assigned User'
  ,SITES_FEES_TYPE_ASSET_DATA.FIELD_10123 as 'Unit Cost'
  ,JBN_ASSET.NAME as 'ASSET_NAME'
  ,0 as 'SORT_ORDER'
  ,COST_ACCOUNT_ASSET.NAME as 'COST_ACCOUNT'
  ,6 as 'SECTION_ORDER'
from
  ASSET JBN_ASSET
  join ASSET_DATA_20 JBN_ASSET_DATA on JBN_ASSET.ASSET_DATA_ID = JBN_ASSET_DATA.ID
    and JBN_ASSET.ASSET_TYPE_ID = 20
  join ASSET_ASSOCIATION AA_JBN_COST_ACCOUNT on JBN_ASSET.ID = AA_JBN_COST_ACCOUNT.ASSET_ID
    and AA_JBN_COST_ACCOUNT.ASSET_FIELD_ID = 10101
  join ASSET COST_ACCOUNT_ASSET on AA_JBN_COST_ACCOUNT.ASSOCIATED_ASSET_ID = COST_ACCOUNT_ASSET.ID
  join ASSET_ASSOCIATION AA_JBN_SITES_FEES_TYPE on JBN_ASSET.ID = AA_JBN_SITES_FEES_TYPE.ASSET_ID
    and AA_JBN_SITES_FEES_TYPE.ASSET_FIELD_ID = 10124
  join ASSET SITES_FEES_TYPE_ASSET on AA_JBN_SITES_FEES_TYPE.ASSOCIATED_ASSET_ID = SITES_FEES_TYPE_ASSET.ID
  join ASSET_DATA_34 SITES_FEES_TYPE_ASSET_DATA on SITES_FEES_TYPE_ASSET.ASSET_DATA_ID = SITES_FEES_TYPE_ASSET_DATA.ID
    and SITES_FEES_TYPE_ASSET.ASSET_TYPE_ID = 34
union all

# JBN Smartphones:
select
  "JBN Smartphones" as 'Item'
  ,SMARTPHONES_TYPE_ASSET.NAME as 'Type'
  ,JBN_ASSET.NAME as 'ID'
  ,JBN_ASSET_DATA.FIELD_10090 as 'Assigned User'
  ,SMARTPHONES_TYPE_ASSET_DATA.FIELD_10121 as 'Unit Cost'
  ,JBN_ASSET.NAME as 'ASSET_NAME'
  ,0 as 'SORT_ORDER'
  ,COST_ACCOUNT_ASSET.NAME as 'COST_ACCOUNT'
  ,7 as 'SECTION_ORDER'
from
  ASSET JBN_ASSET
  join ASSET_DATA_23 JBN_ASSET_DATA on JBN_ASSET.ASSET_DATA_ID = JBN_ASSET_DATA.ID
    and JBN_ASSET.ASSET_TYPE_ID = 23
  join ASSET_ASSOCIATION AA_JBN_COST_ACCOUNT on JBN_ASSET.ID = AA_JBN_COST_ACCOUNT.ASSET_ID
    and AA_JBN_COST_ACCOUNT.ASSET_FIELD_ID = 10086
  join ASSET COST_ACCOUNT_ASSET on AA_JBN_COST_ACCOUNT.ASSOCIATED_ASSET_ID = COST_ACCOUNT_ASSET.ID
  join ASSET_ASSOCIATION AA_JBN_SMARTPHONES_TYPE on JBN_ASSET.ID = AA_JBN_SMARTPHONES_TYPE.ASSET_ID
    and AA_JBN_SMARTPHONES_TYPE.ASSET_FIELD_ID = 10122
  join ASSET SMARTPHONES_TYPE_ASSET on AA_JBN_SMARTPHONES_TYPE.ASSOCIATED_ASSET_ID = SMARTPHONES_TYPE_ASSET.ID
  join ASSET_DATA_33 SMARTPHONES_TYPE_ASSET_DATA on SMARTPHONES_TYPE_ASSET.ASSET_DATA_ID = SMARTPHONES_TYPE_ASSET_DATA.ID
    and SMARTPHONES_TYPE_ASSET.ASSET_TYPE_ID = 33
union all
 

# JBN Wired Phones:
select
  "JBN Wired Phones" as 'Item'
  ,PHONE_TYPE_ASSET.NAME as 'Type'
  ,JBN_ASSET.NAME as 'ID'
  ,JBN_ASSET_DATA.FIELD_10095 as 'Assigned User'
  ,PHONE_TYPE_ASSET_DATA.FIELD_10113 as 'Unit Cost'
  ,JBN_ASSET.NAME as 'ASSET_NAME'
  ,0 as 'SORT_ORDER'
  ,COST_ACCOUNT_ASSET.NAME as 'COST_ACCOUNT'
  ,8 as 'SECTION_ORDER'
from
  ASSET JBN_ASSET
  join ASSET_DATA_26 JBN_ASSET_DATA on JBN_ASSET.ASSET_DATA_ID = JBN_ASSET_DATA.ID
    and JBN_ASSET.ASSET_TYPE_ID = 26
  join ASSET_ASSOCIATION AA_JBN_COST_ACCOUNT on JBN_ASSET.ID = AA_JBN_COST_ACCOUNT.ASSET_ID
    and AA_JBN_COST_ACCOUNT.ASSET_FIELD_ID = 10097
  join ASSET COST_ACCOUNT_ASSET on AA_JBN_COST_ACCOUNT.ASSOCIATED_ASSET_ID = COST_ACCOUNT_ASSET.ID
  join ASSET_ASSOCIATION AA_JBN_PHONE_TYPE on JBN_ASSET.ID = AA_JBN_PHONE_TYPE.ASSET_ID
    and AA_JBN_PHONE_TYPE.ASSET_FIELD_ID = 10111
  join ASSET PHONE_TYPE_ASSET on AA_JBN_PHONE_TYPE.ASSOCIATED_ASSET_ID = PHONE_TYPE_ASSET.ID
  join ASSET_DATA_30 PHONE_TYPE_ASSET_DATA on PHONE_TYPE_ASSET.ASSET_DATA_ID = PHONE_TYPE_ASSET_DATA.ID
    and PHONE_TYPE_ASSET.ASSET_TYPE_ID = 30
union all
 
 
 # JBN Printers
 SELECT 
	 'JBN Printers' as 'Item',
	 A10247.NAME AS 'Type', 
	 ASSET.NAME AS 'ID', 
	 ASSET_DATA_8.FIELD_10310 AS 'Assigned User', 
	 AD10247.FIELD_10270 AS 'Unit Cost', 
	 ASSET.NAME AS 'ASSET_NAME', 
	 0 as 'SORT_ORDER',
	 A10248.NAME AS 'COST_ACCOUNT',
	 8 as 'SECTION_ORDER'
FROM ASSET_DATA_8 
	 LEFT JOIN ASSET ON ASSET_DATA_8.ID = ASSET.ASSET_DATA_ID AND ASSET.ASSET_TYPE_ID=8 
	 LEFT JOIN ASSET ASSET_LOCATION ON ASSET_LOCATION.ID = ASSET.LOCATION_ID  
	 LEFT JOIN ASSET_ASSOCIATION J10247 ON J10247.ASSET_ID = ASSET.ID AND J10247.ASSET_FIELD_ID=10247
	 LEFT JOIN ASSET A10247 ON A10247.ID = J10247.ASSOCIATED_ASSET_ID
	 LEFT JOIN ASSET_DATA_10213 AD10247 ON AD10247.ID = A10247.ASSET_DATA_ID
	LEFT JOIN ASSET_ASSOCIATION J10248 ON J10248.ASSET_ID = ASSET.ID AND J10248.ASSET_FIELD_ID=10248
	 LEFT JOIN ASSET A10248 ON A10248.ID = J10248.ASSOCIATED_ASSET_ID
	 LEFT JOIN ASSET_DATA_15 AD10248 ON AD10248.ID = A10248.ASSET_DATA_ID
	   
union all

 # JBN Scanners
SELECT 
	'JBN Scanners' as 'Item',
	A10317.NAME AS 'Type', 
	ASSET.NAME AS 'ID', 
	ASSET_DATA_10221.FIELD_10322 AS 'Assigned User', 
	AD10317.FIELD_10316 AS 'Unit Cost', 
	ASSET.NAME AS 'ASSET_NAME',
	0 as 'SORT_ORDER',
	A10319.NAME AS 'COST_ACCOUNT',
	8 as 'SECTION_ORDER'  
FROM ASSET_DATA_10221 
	LEFT JOIN ASSET ON ASSET_DATA_10221.ID = ASSET.ASSET_DATA_ID AND ASSET.ASSET_TYPE_ID=10221 
	LEFT JOIN ASSET ASSET_LOCATION ON ASSET_LOCATION.ID = ASSET.LOCATION_ID  
	LEFT JOIN ASSET_ASSOCIATION J10317 ON J10317.ASSET_ID = ASSET.ID AND J10317.ASSET_FIELD_ID=10317
	 LEFT JOIN ASSET A10317 ON A10317.ID = J10317.ASSOCIATED_ASSET_ID
	 LEFT JOIN ASSET_DATA_10220 AD10317 ON AD10317.ID = A10317.ASSET_DATA_ID
	  LEFT JOIN ASSET_ASSOCIATION J10319 ON J10319.ASSET_ID = ASSET.ID AND J10319.ASSET_FIELD_ID=10319
	 LEFT JOIN ASSET A10319 ON A10319.ID = J10319.ASSOCIATED_ASSET_ID
	 LEFT JOIN ASSET_DATA_15 AD10319 ON AD10319.ID = A10319.ASSET_DATA_ID
 
 union all

# User Accounts
select
  "User Account" as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, "") as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,10000 as 'Unit Cost'
  ,USER.USER_NAME as 'ASSET_NAME'
  ,0 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), ".", substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), ".", substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), ".", substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = "Disabled Users") D_USER on USER.ID = D_USER.USER_ID
where
  D_USER.USER_ID is null
union all

# Email Accounts
select
  if((select count(U.ID) from USER U join USER_FIELD_VALUE CA on U.ID = CA.USER_ID and CA.FIELD_ID = 1
  	where U.EMAIL = USER.EMAIL and concat(substring(CA.FIELD_VALUE, 1, 2), ".", substring(CA.FIELD_VALUE, 3, 1), ".", substring(CA.FIELD_VALUE, 4, 3), ".", substring(CA.FIELD_VALUE, 7, 2))
  	= concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), ".", substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), ".", substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), ".", substring(COST_ACCOUNT.FIELD_VALUE, 7, 2))
    group by EMAIL) > 1, "Shared Email Account", "Email Account") as 'Item'
#  "Email Account" as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, "") as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,15000 / (select count(U.ID) from USER U join USER_FIELD_VALUE CA on U.ID = CA.USER_ID and CA.FIELD_ID = 1
  	where U.EMAIL = USER.EMAIL and concat(substring(CA.FIELD_VALUE, 1, 2), ".", substring(CA.FIELD_VALUE, 3, 1), ".", substring(CA.FIELD_VALUE, 4, 3), ".", substring(CA.FIELD_VALUE, 7, 2))
  	= concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), ".", substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), ".", substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), ".", substring(COST_ACCOUNT.FIELD_VALUE, 7, 2))
    group by EMAIL) as 'Unit Cost'  ,USER.USER_NAME as 'ASSET_NAME'
  ,1 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), ".", substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), ".", substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), ".", substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = "Disabled Users") D_USER on USER.ID = D_USER.USER_ID
where
  ifnull(USER.EMAIL, "") not in ("", "noemail@jbn.local") and USER.EMAIL  not like ("%local")
  and D_USER.USER_ID is null
union all

# Internet Accounts
select
  "Internet Account" as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, "") as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,25000 as 'Unit Cost'
  ,USER.USER_NAME as 'ASSET_NAME'
  ,2 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), ".", substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), ".", substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), ".", substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  join USER_LABEL_JT ULJT on USER.ID = ULJT.USER_ID
  join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME in ("LDAP_JBN-Internet-GPO_Germany", "LDAP_JBN-Internet-GPO_local")
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = "Disabled Users") D_USER on USER.ID = D_USER.USER_ID
where
  D_USER.USER_ID is null

union all
# AutoCAD   ##############################################################################
select
  'AutoCAD' as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, '') as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,194000 as 'Unit Cost'
  ,USER.USER_NAME as 'ASSET_NAME'
  ,2 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), '.', substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), '.', substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), '.', substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  join USER_LABEL_JT ULJT on USER.ID = ULJT.USER_ID
  join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME in ('user_LIC-AF-AutoCAD-Users')
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = 'Disabled Users') D_USER on USER.ID = D_USER.USER_ID
where
  D_USER.USER_ID is null
  
  
  union all

# Adobe-Acrobat_DC  Standard 
select
'Adobe-Acrobat_DC_STD' as 'Item'
,USER.EMAIL as 'Type'
,ifnull(EMPLOYEE_ID.FIELD_VALUE, '') as 'ID'
,USER.FULL_NAME as 'Assigned User'
,39000 as 'Unit Cost'
,USER.USER_NAME as 'ASSET_NAME'
,2 as 'SORT_ORDER'
	   ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), '.', substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), '.', substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), '.', substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
,9 as 'SECTION_ORDER'
from
USER
join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
join USER_LABEL_JT ULJT on USER.ID = ULJT.USER_ID
join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME in ('user_LIC-AF-Adobe-Acrobat_Standard-Team-Users')
left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = 'Disabled Users') D_USER on USER.ID = D_USER.USER_ID
where
D_USER.USER_ID is null
union all


# Adobe-ALL-Apps-User   
select
  'Adobe-ALL-Apps-User' as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, '') as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,283000 as 'Unit Cost'
  ,USER.USER_NAME as 'ASSET_NAME'
  ,2 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), '.', substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), '.', substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), '.', substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  join USER_LABEL_JT ULJT on USER.ID = ULJT.USER_ID
  join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME in ('User_LIC-AF-Adobe-ALL-Apps-User')
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = 'Disabled Users') D_USER on USER.ID = D_USER.USER_ID
where
  D_USER.USER_ID is null
 union all

# Adobe-InDesign 
select
  'Adobe-InDesign' as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, '') as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,125000 as 'Unit Cost'
  ,USER.USER_NAME as 'ASSET_NAME'
  ,2 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), '.', substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), '.', substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), '.', substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  join USER_LABEL_JT ULJT on USER.ID = ULJT.USER_ID
  join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME in ('User_LIC-AF-Adobe-InDesign-Users')
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = 'Disabled Users') D_USER on USER.ID = D_USER.USER_ID
where
  D_USER.USER_ID is null
 union all

# Adobe-Photoshop   
select
  'Adobe-Photoshop' as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, '') as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,125000 as 'Unit Cost'
  ,USER.USER_NAME as 'ASSET_NAME'
  ,2 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), '.', substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), '.', substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), '.', substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  join USER_LABEL_JT ULJT on USER.ID = ULJT.USER_ID
  join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME in ('User_LIC-AF-Adobe-Photoshop-Users')
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = 'Disabled Users') D_USER on USER.ID = D_USER.USER_ID
where
  D_USER.USER_ID is null
 union all

# AutoCAD-Civil3D  
select
  'AutoCAD-Civil3D' as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, '') as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,257000 as 'Unit Cost'
  ,USER.USER_NAME as 'ASSET_NAME'
  ,2 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), '.', substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), '.', substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), '.', substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  join USER_LABEL_JT ULJT on USER.ID = ULJT.USER_ID
  join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME in ('User_LIC-AF-AutoCAD-Civil3D-Users')
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = 'Disabled Users') D_USER on USER.ID = D_USER.USER_ID
where
  D_USER.USER_ID is null
 union all

# AutoCAD-LT   
select
  'AutoCAD-LT' as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, '') as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,108000 as 'Unit Cost'
  ,USER.USER_NAME as 'ASSET_NAME'
  ,2 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), '.', substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), '.', substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), '.', substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  join USER_LABEL_JT ULJT on USER.ID = ULJT.USER_ID
  join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME in ('User_LIC-AF-AutoCAD-LT-Users')
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = 'Disabled Users') D_USER on USER.ID = D_USER.USER_ID
where
  D_USER.USER_ID is null
 union all

# Autodesk-AEC-Collection 
select
  'Autodesk-AEC-Collection' as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, '') as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,377000 as 'Unit Cost'
  ,USER.USER_NAME as 'ASSET_NAME'
  ,2 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), '.', substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), '.', substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), '.', substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  join USER_LABEL_JT ULJT on USER.ID = ULJT.USER_ID
  join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME in ('User_LIC-AF-Autodesk-AEC-Collection-Users')
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = 'Disabled Users') D_USER on USER.ID = D_USER.USER_ID
where
  D_USER.USER_ID is null
 union all
# Project   
select
  'Project' as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, '') as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,77000 as 'Unit Cost'
  ,USER.USER_NAME as 'ASSET_NAME'
  ,2 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), '.', substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), '.', substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), '.', substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  join USER_LABEL_JT ULJT on USER.ID = ULJT.USER_ID
  join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME in ('User_LIC-JBN-Project')
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = 'Disabled Users') D_USER on USER.ID = D_USER.USER_ID
where
  D_USER.USER_ID is null
 union all
# Visio   
select
  'Visio' as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, '') as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,38500 as 'Unit Cost'
  ,USER.USER_NAME as 'ASSET_NAME'
  ,2 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), '.', substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), '.', substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), '.', substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  join USER_LABEL_JT ULJT on USER.ID = ULJT.USER_ID
  join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME in ('User_LIC-JBN-Visio')
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = 'Disabled Users') D_USER on USER.ID = D_USER.USER_ID
where
  D_USER.USER_ID is null
 
 union all
# RIB-iTWO   
select
  'RIB-iTWO' as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, '') as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,500000 as 'Unit Cost'
  ,USER.USER_NAME as 'ASSET_NAME'
  ,2 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), '.', substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), '.', substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), '.', substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  join USER_LABEL_JT ULJT on USER.ID = ULJT.USER_ID
  join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME in ('User_ORG-AF-NG-iTWO')
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = 'Disabled Users') D_USER on USER.ID = D_USER.USER_ID
where
  D_USER.USER_ID is null
  
   union all
# SAP-R3 Users 
select
  'SAP_R3' as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, '') as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,331000 as 'Unit Cost'
  ,USER.USER_NAME as 'ASSET_NAME'
  ,2 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), '.', substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), '.', substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), '.', substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  join USER_LABEL_JT ULJT on USER.ID = ULJT.USER_ID
  join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME in ('user_ORG-AF-SAP-R3-User')
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = 'Disabled Users') D_USER on USER.ID = D_USER.USER_ID
where
  D_USER.USER_ID is null
 
    union all
# SAP-4Hana User
select
  'SAP-4Hana' as 'Item'
  ,USER.EMAIL as 'Type'
  ,ifnull(EMPLOYEE_ID.FIELD_VALUE, '') as 'ID'
  ,USER.FULL_NAME as 'Assigned User'
  ,499000 as 'Unit Cost'
  ,USER.USER_NAME as 'ASSET_NAME'
  ,2 as 'SORT_ORDER'
           #,COST_ACCOUNT.FIELD_VALUE as 'COST_ACCOUNT'
           ,concat(substring(COST_ACCOUNT.FIELD_VALUE, 1, 2), '.', substring(COST_ACCOUNT.FIELD_VALUE, 3, 1), '.', substring(COST_ACCOUNT.FIELD_VALUE, 4, 3), '.', substring(COST_ACCOUNT.FIELD_VALUE, 7, 2)) as 'COST_ACCOUNT'
  ,9 as 'SECTION_ORDER'
from
  USER
  join USER_FIELD_VALUE COST_ACCOUNT on USER.ID = COST_ACCOUNT.USER_ID and COST_ACCOUNT.FIELD_ID = 1
  left join USER_FIELD_VALUE EMPLOYEE_ID  on USER.ID = EMPLOYEE_ID.USER_ID  and EMPLOYEE_ID.FIELD_ID  = 2
  join USER_LABEL_JT ULJT on USER.ID = ULJT.USER_ID
  join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME in ('user_ORG-AF-SAP-4Hana-User')
  left join (select USER_ID from USER_LABEL_JT ULJT join LABEL L on ULJT.LABEL_ID = L.ID and L.NAME = 'Disabled Users') D_USER on USER.ID = D_USER.USER_ID
where
  D_USER.USER_ID is null


 
 
 /****** TOTAL ROW ******/

 
   ) ALL_ASSETS
   
   
   --  where
-- /* SET Cost Account Here! for specific cost account*/  ALL_ASSETS.COST_ACCOUNT = "15.0.001.00" 
   
  /* For all cost accounts*/ where ALL_ASSETS.COST_ACCOUNT BETWEEN "11.0.001.00" and "60.0.000.00" AND ALL_ASSETS.COST_ACCOUNT REGEXP '^[0-9]{2}\.[0-9]{1}\.[0-9]{3}\.[0-9]{2}$'

   
 order by
  ALL_ASSETS.COST_ACCOUNT, ALL_ASSETS.SECTION_ORDER, ALL_ASSETS.ASSET_NAME, ALL_ASSETS.SORT_ORDER, ALL_ASSETS.ITEM




"""